/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FallbackLoading: typeof import('./src/components/fallback-loading.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchPagination: typeof import('./src/components/search/SearchPagination.vue')['default']
    SearchResultCard: typeof import('./src/components/search/SearchResultCard.vue')['default']
    SearchResults: typeof import('./src/components/search/SearchResults.vue')['default']
    SearchToolbar: typeof import('./src/components/search/SearchToolbar.vue')['default']
    UApp: typeof import('./../node_modules/.pnpm/@nuxt+ui@4.5.1_@tiptap+exte_45d91d877de7d90058ac2eb9afba016e/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UBadge: typeof import('./../node_modules/.pnpm/@nuxt+ui@4.5.1_@tiptap+exte_45d91d877de7d90058ac2eb9afba016e/node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
    UButton: typeof import('./../node_modules/.pnpm/@nuxt+ui@4.5.1_@tiptap+exte_45d91d877de7d90058ac2eb9afba016e/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCard: typeof import('./../node_modules/.pnpm/@nuxt+ui@4.5.1_@tiptap+exte_45d91d877de7d90058ac2eb9afba016e/node_modules/@nuxt/ui/dist/runtime/components/Card.vue')['default']
    UIcon: typeof import('./../node_modules/.pnpm/@nuxt+ui@4.5.1_@tiptap+exte_45d91d877de7d90058ac2eb9afba016e/node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UInput: typeof import('./../node_modules/.pnpm/@nuxt+ui@4.5.1_@tiptap+exte_45d91d877de7d90058ac2eb9afba016e/node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UPagination: typeof import('./../node_modules/.pnpm/@nuxt+ui@4.5.1_@tiptap+exte_45d91d877de7d90058ac2eb9afba016e/node_modules/@nuxt/ui/dist/runtime/components/Pagination.vue')['default']
    USelect: typeof import('./../node_modules/.pnpm/@nuxt+ui@4.5.1_@tiptap+exte_45d91d877de7d90058ac2eb9afba016e/node_modules/@nuxt/ui/dist/runtime/components/Select.vue')['default']
    UTable: typeof import('./../node_modules/.pnpm/@nuxt+ui@4.5.1_@tiptap+exte_45d91d877de7d90058ac2eb9afba016e/node_modules/@nuxt/ui/dist/runtime/components/Table.vue')['default']
  }
}

// For TSX support
declare global {
  const FallbackLoading: typeof import('./src/components/fallback-loading.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const SearchPagination: typeof import('./src/components/search/SearchPagination.vue')['default']
  const SearchResultCard: typeof import('./src/components/search/SearchResultCard.vue')['default']
  const SearchResults: typeof import('./src/components/search/SearchResults.vue')['default']
  const SearchToolbar: typeof import('./src/components/search/SearchToolbar.vue')['default']
  const UApp: typeof import('./../node_modules/.pnpm/@nuxt+ui@4.5.1_@tiptap+exte_45d91d877de7d90058ac2eb9afba016e/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
  const UBadge: typeof import('./../node_modules/.pnpm/@nuxt+ui@4.5.1_@tiptap+exte_45d91d877de7d90058ac2eb9afba016e/node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
  const UButton: typeof import('./../node_modules/.pnpm/@nuxt+ui@4.5.1_@tiptap+exte_45d91d877de7d90058ac2eb9afba016e/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
  const UCard: typeof import('./../node_modules/.pnpm/@nuxt+ui@4.5.1_@tiptap+exte_45d91d877de7d90058ac2eb9afba016e/node_modules/@nuxt/ui/dist/runtime/components/Card.vue')['default']
  const UIcon: typeof import('./../node_modules/.pnpm/@nuxt+ui@4.5.1_@tiptap+exte_45d91d877de7d90058ac2eb9afba016e/node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
  const UInput: typeof import('./../node_modules/.pnpm/@nuxt+ui@4.5.1_@tiptap+exte_45d91d877de7d90058ac2eb9afba016e/node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
  const UPagination: typeof import('./../node_modules/.pnpm/@nuxt+ui@4.5.1_@tiptap+exte_45d91d877de7d90058ac2eb9afba016e/node_modules/@nuxt/ui/dist/runtime/components/Pagination.vue')['default']
  const USelect: typeof import('./../node_modules/.pnpm/@nuxt+ui@4.5.1_@tiptap+exte_45d91d877de7d90058ac2eb9afba016e/node_modules/@nuxt/ui/dist/runtime/components/Select.vue')['default']
  const UTable: typeof import('./../node_modules/.pnpm/@nuxt+ui@4.5.1_@tiptap+exte_45d91d877de7d90058ac2eb9afba016e/node_modules/@nuxt/ui/dist/runtime/components/Table.vue')['default']
}